[package]
name = "catsh"
version = "0.1.0"
authors = ["JheysonDev <JheysonDev@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "7.0.0"
colored = "2.0.0"